version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: centinote
      POSTGRES_PASSWORD: insecure
    restart: always
