version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:8080"
    environment:
      CENTINOTE_DB_HOST: "db"
      CENTINOTE_DB_DATABASE: "centinote"
      CENTINOTE_DB_USERNAME: "postgres"
      CENTINOTE_DB_PASSWORD: "insecure"
      TZ: "Asia/Seoul"
    restart: always
  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Seoul"
      POSTGRES_DB: "centinote"
      POSTGRES_PASSWORD: "insecure"
    restart: always
volumes:
  db:
