version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:8080"
    restart: always
  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: centinote
      POSTGRES_PASSWORD: insecure
    restart: always
volumes:
  db:
